# Generated by Django 2.1.1 on 2018-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_remove_point_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='predicted_category',
            field=models.IntegerField(default=-1),
        ),
    ]
